dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
before_script:
  - npm install -g nsp
  - nsp check
script:
   - npm run lint
   - npm run test
branches:
  only:
    - master
    - /^greenkeeper/.*$/